//  Copyright (c) 2026 Uber Technologies, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package main

import (
	"bufio"
	"bytes"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"os"
	"os/exec"
	"path/filepath"
	"strconv"
	"strings"
)

// GoVetDriver implements Driver for running NilAway through go vet.
type GoVetDriver struct{}

// Run runs NilAway through go vet on the test project and returns the diagnostics.
func (d *GoVetDriver) Run(dir string) (map[Position][]string, error) {
	cwd, err := os.Getwd()
	if err != nil {
		return nil, fmt.Errorf("get current working directory: %w", err)
	}

	if out, err := exec.Command("make", "build").CombinedOutput(); err != nil {
		return nil, fmt.Errorf("build NilAway: %w: %q", err, string(out))
	}

	tempRoot := filepath.Dir(dir)
	goCacheDir := filepath.Join(tempRoot, "go-vet-cache")
	goTempDir := filepath.Join(tempRoot, "go-vet-tmp")
	for _, path := range []string{goCacheDir, goTempDir} {
		if err := os.MkdirAll(path, 0755); err != nil {
			return nil, fmt.Errorf("create temporary Go directory %q: %w", path, err)
		}
	}
	cmd := exec.Command(
		"go", "vet",
		"-vettool="+filepath.Join(cwd, "bin", "nilaway"),
		"-json",
		"-pretty-print=false",
		// Disable group error messages to make the output accurate for comparisons.
		"-group-error-messages=false",
		"-exclude-file-docstrings=@generated,Code generated by",
		"-include-errors-in-files="+dir,
		"./...",
	)
	cmd.Dir = dir
	cmd.Env = append(cmd.Environ(),
		"GOCACHE="+goCacheDir,
		"GOCACHEPROG=",
		"GOTMPDIR="+goTempDir,
	)
	out, err := cmd.CombinedOutput()
	if err != nil {
		return nil, fmt.Errorf("run go vet: %w\n%s", err, string(out))
	}

	return parseGoVetOutput(out, dir)
}

func parseGoVetOutput(output []byte, dir string) (map[Position][]string, error) {
	var jsonOutput bytes.Buffer
	sc := bufio.NewScanner(bytes.NewReader(output))
	for sc.Scan() {
		if strings.HasPrefix(sc.Text(), "# ") {
			continue
		}
		jsonOutput.WriteString(sc.Text())
		jsonOutput.WriteByte('\n')
	}
	if err := sc.Err(); err != nil {
		return nil, fmt.Errorf("scan go vet output: %w", err)
	}

	collected := make(map[Position][]string)
	decoder := json.NewDecoder(&jsonOutput)
	for {
		type diagnostic struct {
			Posn    string `json:"posn"`
			Message string `json:"message"`
		}
		var result map[string]map[string][]diagnostic
		if err := decoder.Decode(&result); errors.Is(err, io.EOF) {
			break
		} else if err != nil {
			return nil, fmt.Errorf("decode go vet output: %w", err)
		}

		for _, analyzers := range result {
			for _, diagnostic := range analyzers["nilaway"] {
				parts := strings.Split(diagnostic.Posn, ":")
				if len(parts) < 3 {
					return nil, fmt.Errorf("expect at least 3 parts in position string, got %+v", diagnostic)
				}
				line, err := strconv.Atoi(parts[len(parts)-2])
				if err != nil {
					return nil, fmt.Errorf("convert line number: %w", err)
				}
				pos, err := PositionInProject(dir, strings.Join(parts[:len(parts)-2], ":"), line)
				if err != nil {
					return nil, err
				}
				collected[pos] = append(collected[pos], diagnostic.Message)
			}
		}
	}

	return collected, nil
}
