//  Copyright (c) 2023 Uber Technologies, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package main

import (
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
)

// StandaloneDriver implements Driver for running NilAway as a standalone binary.
type StandaloneDriver struct{}

// Run runs NilAway as a standalone binary on the test project and returns the diagnostics.
// The standalone binary delegates direct invocations through `go vet -vettool=<self>`, so its
// JSON output is the same per-package streaming format that parseDriverOutput handles.
func (d *StandaloneDriver) Run(dir string) (map[Position][]string, error) {
	cwd, err := os.Getwd()
	if err != nil {
		return nil, fmt.Errorf("get current working directory: %w", err)
	}

	// Build NilAway first.
	if out, err := exec.Command("make", "build").CombinedOutput(); err != nil {
		return nil, fmt.Errorf("build NilAway: %w: %q", err, string(out))
	}

	// Run the NilAway binary on the test project, with redirects to an internal buffer.
	cmd := exec.Command(filepath.Join(cwd, "bin", "nilaway"),
		"-json", "-pretty-print=false",
		// Disable group error messages to make the output accurate for comparisons.
		"-group-error-messages=false",
		"-exclude-file-docstrings=@generated,Code generated by",
		"./...",
	)
	cmd.Dir = dir
	out, err := cmd.CombinedOutput()
	if err != nil {
		return nil, fmt.Errorf("run nilaway: %w\n%s", err, string(out))
	}

	return parseDriverOutput(out, dir)
}
